do_fetch
cmake \
	-DCMAKE_SYSTEM_NAME=Windows \
	-DCMAKE_INSTALL_PREFIX=$prefix \
	-DCMAKE_FIND_ROOT_PATH=$prefix \
	-DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
	-DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
	-DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
	-DBUILD_SHARED_LIBS=no .
do_make
rm $prefix/bin/fluidsynth.exe
